### ISSUE TITLE
Approach to Liquidity on tokens page

### ISSUE THREAD

**Issue by Velua** [EOS-Nation/xnation-ui#101]
The Bancor.network page will add up all the liquidity the BNT token has across all relays holding BNT and display that in the liquidity cell.

Do we want to replicate this on the ETH tokens page for the next update, and if so, do we want to do this across all the other tokens as well? 

So relays containing ANT tokens

Relay 1:
ANT liquidity $500

Relay2
ANT liquidity $300

Tokens page...
Liquidity : $800

Or, liquidity is calculated by that of the highest relay, which would be $500.

**Comment by Velua** [comment]
The benefits of the $800 option would be an overview of a tokens popularity, however, one then couldn't use it as an accurate idea of what slippage to expect, they'd just have to type in the desired amount before the UI calculates it.

**Comment by DenisCarriere** [comment]
If we’re doing a “total” liquidity I would add up all BNT pools, regardless if it’s a duplicate.

Do a SUM of all the BNT in all the relays combined

**Comment by Velua** [comment]
We are going ahead with adding up all token liquidity. Replementing code.
