### ISSUE TITLE
1 unit conversion rates

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/xnation-ui#104]
The unit conversion rate should be based on the input amount relative to the output.

In this example:

Input: `10 ETH`
Output: `9026.543162462537845529 BNT`
Conversion rate should be: `1 ETH = 902.6543 BNT`

Also USD price should reflect the new conversion rate

<img width="908" alt="Screen Shot 2020-04-23 at 2 27 10 PM" src="https://user-images.githubusercontent.com/550895/80135709-94595280-856e-11ea-8bab-5e19fdedf50a.png">

**Comment by Velua** [comment]
Understood!
