### ISSUE TITLE
Automatic `get_currency_balance` fetch when selecting token from dropdown menu

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/xnation-ui#107]
Whenever user selects a token as their selection.

We should automatically `get_currency_balance` for that particular token.

Can be applied in EOS for the following tabs:
- create
- convert
- pools

If they select BNT, fetch BNT.

Everytime a token is selected from the dropdown, an automatic `get_currency_balance` should be called on that token.

**Comment by Velua** [comment]
Made fetching more frequent, on the pools page this will behave on tokens changed, so if you switch between 3 relays all containing BNT as a reserve it's only gonna call BNT the once, other 3 tokens will be called 3 times. 
Deployed at 1.0.02

**Comment by DenisCarriere** [comment]
Noticed you are doing multiple API calls using `v2/state/get_tokens`

If you call that endpoint, you only need to do 1 HTTP call

However, the most up to date currency balance information will come `v1/chain/get_currency_balance`

Try to use the logic of:
- When querying 1 or 2 tokens => use `v1/get_currency_balance`
- When querying full token balance of user => use `v2/get_tokens`

**Comment by DenisCarriere** [comment]
Hyperion can sometimes have a long delay in fetching token balances, so it's always best to query single token balances using the native `get_currency_balance` if it's only 1 or 2 http calls

**Comment by Velua** [comment]
Should be fixed, to double check/test.

**Comment by Velua** [comment]
Been playing around long enough, happy with the performance of this one.
