### ISSUE TITLE
SX dynamic prices instead of using pegged price

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/xnation-ui#109]
Instead of using the pegged price, it would be better to calculate the price of each asset based on 1 USDT.

```js
get_price( "1.0000 USDT", "EOSDT", pools );
```

And of course USDT price would be the base price as `1.0000 USD`

Also trim the USD price to maximum of 4 decimals `1.1234 USD`

![image](https://user-images.githubusercontent.com/550895/80289222-43329580-870b-11ea-8f2b-b537baaa1ada.png)

**Comment by Velua** [comment]
Just to confirm it's ```get_price``` you want here and not ```get_rate``` ?

**Comment by DenisCarriere** [comment]
Yea use `get_price`, not trying to price in fees in this column, it's just a price gauge of $1

**Comment by Velua** [comment]
Done.
Deployed in beta release https://github.com/EOS-Nation/xnation-ui/releases/tag/v1.0.03-beta

**Comment by DenisCarriere** [comment]
Awesome! 👍

**Comment by DenisCarriere** [comment]
![image](https://user-images.githubusercontent.com/550895/80293827-172a0b00-8731-11ea-93b0-3b014997d702.png)

You trimmed a bit too much, USD price should be 4 precisions and not 2

**Comment by Velua** [comment]
Now 4!
