### ISSUE TITLE
Remove 24 hour change in SX

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/xnation-ui#110]
Since that feature isn't available yet, would be better to disable it temporarily for now.

![image](https://user-images.githubusercontent.com/550895/80289280-a9b7b380-870b-11ea-8607-d9c9a6b6ab58.png)

**Comment by Velua** [comment]
This has been accomplished by the table component checking for truthiness in the properties, if all rows are falsy it won't render the header at all. 
Deployed in beta release https://github.com/EOS-Nation/xnation-ui/releases/tag/v1.0.03-beta
