### ISSUE TITLE
Inverse Price & update price per unit

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/xnation-ui#114]
The output is correct, however the middle should be

`1 USDB = 0.961687 USDT`

<img width="936" alt="Screen Shot 2020-05-05 at 9 24 23 PM" src="https://user-images.githubusercontent.com/550895/81130749-dd1ded80-8f16-11ea-889a-ab3fc9805350.png">

`1 USDB = 1.0307 USDT` seems off

Should be

`1 USDB = 1.0225 USDT`

![image](https://user-images.githubusercontent.com/550895/81130783-fb83e900-8f16-11ea-821d-cdbd5d065ebf.png)

The expected price seem like they need to be inversed.

```
1 / calculate_out
```

![image](https://user-images.githubusercontent.com/550895/81130712-bbbd0180-8f16-11ea-8bc3-ebc7620a3844.png)

**Comment by Velua** [comment]
Makes sense

**Comment by Velua** [comment]
Sorted this out together.
