### ISSUE TITLE
Split slippage & fee into two metrics

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/xnation-ui#131]
### Before:

![image](https://user-images.githubusercontent.com/550895/84199256-d54fec80-aa72-11ea-9b20-59a75c93b549.png)

### After:
slippage: 0.25%
fee = 0.05 USDT

The slippage should be calculated solely on the price increase based on the size of the input, the trading fees shouldn't be included in this slippage calculations.

@DenisCarriere needs to update sx.js to reflect these changes.

**Comment by Velua** [comment]
Now deployed beta.
