### ISSUE TITLE
Merge SX liquidity pools

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/xnation-ui#133]
If we can merge the liquidity pools together into the USD(S) section:

- eosdt.sx
- vigor.sx
- stable.sx
- usde.sx (not deployed yet)

https://xnation.io/usds?base=USDT&quote=EOSDT

Also, we can aggregate the "liquidity depth" from each token and display the combined depth of all pools.

For example, EOSDT is present in all 3 pools, the depth would be 200 + 2500 + 3000 (5200 EOSDT)

**Comment by Velua** [comment]
Sounds good, just about to finish unique token refactoring, will jump on this soon

**Comment by DenisCarriere** [comment]
Perfect 👌

**Comment by Velua** [comment]
Now in beta.
