### ISSUE TITLE
Using registry.sx to auto-detect SX pools

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/xnation-ui#135]
I've deployed a Registry smart contract which will have all the SX pools available and their supported tokens.

- https://github.com/stableex/sx.registry
- https://bloks.io/account/registry.sx

This help with merging liquidity pools together https://github.com/EOS-Nation/xnation-ui/issues/133

## TABLE `swap`

- `{name} contract` - swap contract account name
- `{set<symbol_code>} tokens` - supported tokens

### example

```json
{
    "contract": "eosdt.sx",
    "tokens": ["EOS", "EOSDT", "USDT"]
}
```

**Comment by Velua** [comment]
Filtering out ```swap.sx``` for now.
