### ISSUE TITLE
Beta to Prod migration

### ISSUE THREAD

**Issue by Velua** [EOS-Nation/xnation-ui#139]

**Comment by Velua** [comment]
@DenisCarriere All tasks in this mile stone are complete and present in beta, leaving this open to get your approval before sending into prod.

**Comment by DenisCarriere** [comment]
Sent out a few comments over telegram regarding the newest updates

- upgrade sx.js library to v2.2.2 to fix slippage and removed error checks on get_rate
- on your side if you can check the “volume” numbers, they don’t seem to be accurate at the moment

**Comment by Velua** [comment]
Update now pushed.
