### ISSUE TITLE
include extended symbol in registry.sx

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/xnation-ui#144]
## TABLE `swap`

- `{name} contract` - swap contract account name
- `{set<symbol_code>} tokens` - supported tokens
- `{set<extended_symbol>} ext_tokens` - supported extended symbols

### example

```json
{
    "contract": "swap.sx",
    "tokens": ["EOS", "EOSDT", "USDT"],
    "ext_tokens": [
        { "sym": "4,EOS", "contract": "eosio.token" },
        { "sym": "4,USDT", "contract": "tethertether" },
        { "sym": "9,EOSDT", "contract": "eosdtsttoken" }
    ]
}
```

https://bloks.io/account/registry.sx?loadContract=true&tab=Tables&table=swap&account=registry.sx&scope=registry.sx&limit=100

**Comment by Velua** [comment]
Now adopted in prod & beta, happy for ```tokens``` to get decommissioned.

**Comment by DenisCarriere** [comment]
Perfect! 👌 

I’ll keep “tokens” kicking around for now, it’s not much extra data
