### ISSUE TITLE
Charts Data

### ISSUE THREAD

**Issue by pingustar** [EOS-Nation/xnation-ui#168]
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/7262066/88422741-fc783880-cdea-11ea-8130-e78594c66915.png">

- [ ] EOS Liquidity

- [ ] EOS Volume

- [ ] ETH Liquidity

- [ ] ETH Volume

**Comment by Velua** [comment]
Decomission, can re-assess our approach to this later.
