### ISSUE TITLE
Confirm Pool data

### ISSUE THREAD

**Issue by pingustar** [EOS-Nation/xnation-ui#170]
<img width="507" alt="image" src="https://user-images.githubusercontent.com/7262066/88458996-2fc1d280-ce92-11ea-8e84-fa0bec1e8c1e.png">

- [ ] Pool Token amount received back

- [ ] Rate Token 1

- [ ] Rate Token 2

- [ ] Share

**Comment by Velua** [comment]
Try this out now from bancor-product, re-open if there's any issues.
