### ISSUE TITLE
Display profit/loss of relays

### ISSUE THREAD

**Issue by chillsauce** [EOS-Nation/xnation-ui#64]
This functionality is being developed by a 3rd party but should be seamlessly integrated into the xnation Portal. See example: https://zumzoom.github.io/analytics/uniswap/providers.html

**Comment by chillsauce** [comment]
I'm not aware of any profit/loss tool on EOS. 
On ETH you can use zumzoom / zerion APIs to get this data.

zumzoom: https://zumzoom.github.io/analytics/bancor/roi.html
zerion: app.zerion.io

they have no docs but we can work with teams to get you what you need on ETH

**Comment by Velua** [comment]
Do we have any ideas on how we want this to look design wise?

**Comment by Velua** [comment]
We've now got this running on the latest beta build, check it out and let me know what you think. @DenisCarriere @chillsauce

**Comment by Velua** [comment]
Awaiting feedback on beta version @DenisCarriere @chillsauce

**Comment by Velua** [comment]
Feedback 👍 
Need to have adaptable returns when changing to months.
Rename Return to ROI.

**Comment by Velua** [comment]
@DenisCarriere @chillsauce Final thoughts on this? Now reflective in prod. 

Awaiting feedback from Nate about his request to have ROI change based on the zoom level of the graph.
