### ISSUE TITLE
Enable purchasing of USDB

### ISSUE THREAD

**Issue by chillsauce** [EOS-Nation/xnation-ui#65]

**Comment by Velua** [comment]
ETH or EOS?

**Comment by chillsauce** [comment]
I suppose both. We can discuss on our next call.

**Comment by Velua** [comment]
Let's follow up with the scope of this one.

**Comment by Velua** [comment]
Awaiting further information on this, I believe we're further defining what purchasing USDB means?

**Comment by Velua** [comment]
Closing for now.
