### ISSUE TITLE
Multi-USDB relay sort by highest liquidity

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/xnation-ui#82]
Sort by highest liquidity also on Multi-Converter contract, assume that there will be more than 1 relay with the same liquidity:

- BNT/USDB (BNTUSD)
- BNT/USDB (TESTING)

Also, we should exclude relays with duplicate reserves and lowest liquidity depth (TESTING would be automatically excluded from the list).

**Comment by DenisCarriere** [comment]
![image](https://user-images.githubusercontent.com/550895/77482824-2d287100-6dfd-11ea-8159-6926c3930c34.png)

**Comment by Velua** [comment]
Okay, so essentially when it comes to trading, exclude duplicate relays. However, duplicate relays should still be around on the Relays page, that way they can still be administered admin and liquidity wise?

**Comment by Velua** [comment]
To double check.

**Comment by Velua** [comment]
Can confirm that we've got a relays list, which **will** include relays of duplicate reserves, however, when performing a conversion, out of these relays it will eliminate duplicate reserve relays with highest liquidity being the winner.
