### ISSUE TITLE
Updates to sx.js

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/xnation-ui#94]
Updates dependencies:
- `sx.js@0.6.0`
- `eos-common@0.7.6`

Added error handling for:
- pool ratio must be lower than 500%
- pool ratio must be above 20%

Also, I've updated the `get_rate()` outputs

- get_rate => out & fee
- get_inverse_rate => quantity & fee

🐛 One more thing that's different with the get_rate is you don't need to deduct the fee, it's already being deducted (you're deducting the fees twice in the UI)

**Comment by Velua** [comment]
this doesn't include slippage then?

**Comment by DenisCarriere** [comment]
Correct, it doesn't include slippage, however I'm working on that right now

I'll include `slippage` output in the `get_rate`

Working on the math to make that work right now.

**Comment by DenisCarriere** [comment]
Added `get_slippage` method and `slippage` is a new output of both `get_rate` & `get_inverse_rate`

https://github.com/stableex/sx.js/blob/master/examples/get_rate.ts#L12

**Comment by Velua** [comment]
Pending next release

**Comment by DenisCarriere** [comment]
😎 sweet looking forward to this update
