### ISSUE TITLE
Token balance not showing up

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/xnation-ui#95]
Instead of showing nothing, we should still show "0 token" balance and still display 0% - 100% (without it it looks like there's a bug and it wasn't able to fetch the token balance).

![image](https://user-images.githubusercontent.com/550895/78706032-645a5000-78dc-11ea-90f4-1ed313a67350.png)

**Comment by Velua** [comment]
Component now has a default prop balance of 0, currently says 
![Screenshot at 2020-04-08 17:11:01](https://user-images.githubusercontent.com/8017434/78755095-f422fb80-79bb-11ea-8964-28bfa36ef2a5.png)

Doesn't include the 0 25 50 100% thing, not worth it if those buttons won't work is it?

**Comment by Velua** [comment]
That is fine.
