### ISSUE TITLE
Selecting BNT - error entire reserve

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/xnation-ui#96]
Still getting the error of USDB/BNT pools

Happens when you enter BNT on the right hand side

https://beta.xnation.io/eos?base=USDB&quote=BNT

![image](https://user-images.githubusercontent.com/550895/78716192-88be2880-78ec-11ea-8c5b-bf795f84aad7.png)

**Comment by Velua** [comment]
Fixed, pending next release.

**Comment by Velua** [comment]
I lied, next release, just getting all my ducks in a row.
